[package]
name = "aoc-24-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.11.0"
regex = "1.11.1"


[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "main_bench"
harness = false
